# Generated by Django 4.0.2 on 2022-02-16 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=200)),
                ('conteudo', models.CharField(max_length=1000)),
                ('mapa_mental', models.ImageField(upload_to='imagens/%d/%m')),
                ('data_postagem', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
