# Generated by Django 4.0.2 on 2022-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
